services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d/
volumes:
  postgres_data: